name: DB Intigration

on:
  push:
    paths:
      - 'APIServer/Migrations/**'
      
jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build
        run: dotnet build APIServer/APIServer.csproj --configuration Release

      - name: EF Migrate
        run: dotnet ef database update --project APIServer/APIServer.csproj
        env:
          # RDS DB 접속 정보는 GitHub Secrets에서 주입
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
